# Generated by Django 4.2.1 on 2025-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='drive',
            field=models.CharField(choices=[('0', 'front wheel drive'), ('1', 'rear wheel drive'), ('2', 'four-wheel drive')], default=('0', 'front wheel drive'), max_length=100, verbose_name='drive'),
        ),
    ]
