# Generated by Django 4.2.1 on 2025-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='fuel_type',
            field=models.CharField(choices=[('бензин', 'gasoline'), ('дизель', 'diesel'), ('водород', 'hydrogen'), ('электро', 'electro')], default=('бензин', 'gasoline'), max_length=100),
        ),
    ]
