# Generated by Django 5.1.6 on 2025-08-31 03:18

import auto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_comment_delete_comments_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='production_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1960), auto.models.max_value_current_year]),
        ),
    ]
