# Generated by Django 5.1.6 on 2025-09-13 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_production_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Mileage'),
        ),
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='auto',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Drom URL'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel_tank_capacity',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(5, message='Min 5 liters'), django.core.validators.MaxValueValidator(10000, message='Max 10000 liters')]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='numbers_of_seats',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2, 'Min 2 seats'), django.core.validators.MaxValueValidator(9, 'Max 9 seats')], verbose_name='Numbers of seats'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='trunk_capacity',
            field=models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(1000, message='Max 1000 kg'), django.core.validators.MinValueValidator(100, message='Min 100 kg')], verbose_name='Trunk_capacity'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='wheel_size',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(10, message='Min 10R'), django.core.validators.MaxValueValidator(25, message='Max 25R')], verbose_name='Wheel size'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='title',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Transmission title'),
        ),
    ]
